### ISSUE TITLE
[Suggestion]: instances instead of strings

### ISSUE THREAD

**Issue by timreichen** [oslabs-beta/dashport#39]
This project looks great.
Is there a reason why we pass strings instead of instances other than passportjs conventions? I never quiet understood why it needed that. Since the strategies have their own classes (`GoogleStrategy ` etc.), I would expect dashport to have the same. Something like
```ts
const dashport = new OakDashport();
```
instead of
```ts
const dashport = new Dashport('oak');
```

Also, since the strategies instances are created anyway, why not pass the instance instead of a string? if we want to be sure about passing the correct string, we might need an export `export const strategyString = "goog"` anyway, so why not use the instance itself?

```ts
export const strategy = new GoogleStrategy({
  client_id: 'client-id-here',
  redirect_uri: 'redirect-uri-here', 
  response_type: 'response-type-here', 
  scope: 'scopes-wanted-here',
  client_secret: 'client-secret-here',
  grant_type: 'grant-type-here',
})
```
and
```ts
dashport.authenticate(strategy)
```
instead of 
```ts
dashport.addStrategy('goog', new GoogleStrategy({
  client_id: 'client-id-here',
  redirect_uri: 'redirect-uri-here', 
  response_type: 'response-type-here', 
  scope: 'scopes-wanted-here',
  client_secret: 'client-secret-here',
  grant_type: 'grant-type-here',
}));
```
and
```ts
dashport.authenticate('goog')
```

Same with `dashport.addSerializer ` and `dashport.addDeserializer`, though I don't know why they need to have names since only their values are read. Maybe I am missing something, why we need to add strategies and serializers and deserializers instead of passing them when they are needed:
```ts
const strategy = …
const serializer = …
const deserializer = …
export const googleAuthentication = { strategy, serializers: [serializer], deserializers: [deserializer] }
```
```ts
dashport.authenticate(googleAuthentication)
```
or something similar to that.

What do you think?

**Comment by alcheng005** [comment]
In Dashport, strings are passed into initializations to keep Dashport flexible. When the string is passed in, the Dashport constructor assigns the this._framework property to be the string. Then it passes the string to a SessionManager initialization and two methods to determine the functionality of this._sm and Dashport's initialize and authenticate properties. When SessionManager and the two methods are run, there are checks in place to see if the value of the string is supported in Dashport. Supported meaning, since Dashport's authenticate and initialize methods are supposed to function as middleware, we need to ensure the authenticate and initialize methods fit the structure of that framework. So for Oak, it's (ctx, next). If Express worked for Deno it would be (req, res, next). The way a server framework handles the HTTP object also affects how we structure the functionality as well. For Oak, the ctx.state property persists so we're able to take advantage of that to persist a Dashport session, but if another framework was being used, we wouldn't have access to the persistent ctx.state property.

So to get to the actual meat of your first suggestion, we could separate Dashport into different classes and export OakDashport to have just Oak functionality. Then when more alternatives to Oak appear, we could create a different Dashport class for each of them. However, this would end up causing us to copy/paste the code for Dashport and SessionManager and creating new files for them every time a new server framework were to be added. This would make maintainability more complicated since the Dashport team would have to look through and edit multiple files to make any future changes. By keeping the checks to be inside one singular Dashport class, it helps maintainability.

We believe the way Dashport is structured now with the checks also makes it easier for any developer to add their own server framework logic. Since Deno is relatively new, it's unsure what frameworks will become popular. Right now it's Oak, but it could be another framework in the near future. As a team of five, we won't be able to handle adding every new framework, but if a developer wants to use a server framework not supported, they can just add in their checks and logic wherever a check for Oak is happening.

Albeit, having these checks inside Dashport creates a bigger file size to download for developers, but we believe it's a tradeoff worth having. And this is an opinion, but it seems simpler to have one Dashport class than creating multiple files for multiple Dashport classes. But we'd love to discuss and hear more of your thoughts on this. What do you think of our reasoning?

For the second suggestion, this is one we'll have to think about more. Can you elaborate more on the benefits of using the instances directly? In your example with

```typescript
export const strategy = new GoogleStrategy({
  client_id: 'client-id-here',
  redirect_uri: 'redirect-uri-here', 
  response_type: 'response-type-here', 
  scope: 'scopes-wanted-here',
  client_secret: 'client-secret-here',
  grant_type: 'grant-type-here',
})

dashport.authenticate(strategy)
```

Dashport would no longer store the strategies within the class. So in order to use a strategy, the strategy would have to be declared and assigned within the same file the Dashport middleware would be used. This would clutter up the file(s) handling the routing with code that doesn't pertain to routing. An alternative would be to declare and assign the strategy in another file and then import it into the routing file(s) to be referred to wherever Dashport.authenticate needs to be used.

By storing strategies with names into the Dashport class, all Dashport-related setup can be done in a singular Dashport configuration file, and then that Dashport instance can be exported wherever it needs to be used. Then when Dashport.authenticate is used, the name of the strategy can be passed in and the correct strategy will be used. This is important if the developer wants to use multiple strategies. All strategies can be added in this config file, and then exported for use, versus having to define strategies or exporting/importing strategies where they need to be used. We believe our implementation helps keep the code modular since the only thing a developer would ever have to import to other files is the Dashport instance they've configured.

As for addSerializer and addDeserializer, currently, only the first serializer and deserializer added in can be used. However, we want to refactor this in the future to allow calling serializers and deserializers by name, our reasoning is similar to above with the strategies. With your last example

```typescript
export const googleAuthentication = { strategy, serializers: [serializer], deserializers: [deserializer] }
```

If a developer wanted to use multiple strategies, they would have to pass in the same serializer and deserializers to each authentication variable, which we believe breaks the DRY principle, since the only thing different would be the strategies. By keeping the strategies, serializers, and deserializers, all stored within Dashport, all strategies, serializers, and deserializers, only have to be defined once and can be used however the developer wishes to match them.

However, this is just how we currently see it, and we know there's always room for improvement. Again, we definitely would love to have a discussion on this and consider all the ways we can make Dashport better. And thanks for submitting and being our first issue!

**Comment by timreichen** [comment]
@alcheng005 thanks for your detailed answer.

# about framekwork classes 
The idea behind having separate classes for each framework would be that they can be extended upon a base class, so no code needs to be copied and the framework class only contains framework specific code. In that sense the files would be more readable and imo better maintainable.
If you wanted to create a dashport framework as a 3rd party, you could just extend the base class as easily.
Atm the code checks what framework is used (only 'oak' is valid at the moment). Imagine there were 100 supported  frameworks. The `authenticate` method would basically become a huge `switch` statement. 
>Albeit, having these checks inside Dashport creates a bigger file size to download for developers, but we believe it's a tradeoff worth having. And this is an opinion, but it seems simpler to have one Dashport class than creating multiple files for multiple Dashport classes. But we'd love to discuss and hear more of your thoughts on this. What do you think of our reasoning?

I think there is no reason why it needed to be that way. I normally only use one framework at a time, so having `OakDashport` or `ExpressDashport` (if it were supported) instead of a file that contains code for all frameworks that I am never going to use makes more sense to me.

# about strategy instance passings
>For the second suggestion, this is one we'll have to think about more. Can you elaborate more on the benefits of using the instances directly?

The main idea instance passing instead of strings is to avoid the need to name things twice. You have variable/constant names, why would you need to have a string based name as well?

>Dashport would no longer store the strategies within the class. So in order to use a strategy, the strategy would have to be declared and assigned within the same file the Dashport middleware would be used.

The instance would not have to be declared in the middleware framework, because instances can be exported and imported from files. So you can do
```ts
// google_strategy.ts
export const strategy = new GoogleStrategy({
  client_id: 'client-id-here',
  redirect_uri: 'redirect-uri-here', 
  response_type: 'response-type-here', 
  scope: 'scopes-wanted-here',
  client_secret: 'client-secret-here',
  grant_type: 'grant-type-here',
})
```

```ts
// auth.ts
import { strategy } from "./path/to/google_strategy.ts"

dashport.authenticate(strategy)
```

Or you can declare all strategies in one strategies file
```ts
// strategies.ts
export const googleStrategy = new GoogleStrategy(…)
export const otherStrategy = new OtherStrategy(…)
export const someOtherStrategy = new SomeOtherStrategy(…)
```
```ts
// auth.ts
import * as strategies from "./path/to/strategies.ts"

dashport.authenticate(strategy.googleStrategy)
```

So this would actually help making the setup modular. I think adding them to a `dashport` instance which just stores it without the need to store them makes it more complicated than it needs to be.

# about (de)serializes
> As for addSerializer and addDeserializer, currently, only the first serializer and deserializer added in can be used. However, we want to refactor this in the future to allow calling (de)serializers by name, our reasoning is similar to above with the strategies.

There would be no need for that if you pass the (de)serializer directly. The paring of strategies and (de)serializers should be done outside the dashport class imo. Since functions can be exported as well, this should be no problem either. Again, makes it more modular:

```ts
// serializer.ts
export function serializer() {…}
export function deserializer() {…}
```

```ts
import { serializer, deserializer } from "./path/to/serializer.ts"
export const googleAuthentication = { googleStrategy, serializer, deserializer }
export const otherAuthentication = { otherStrategy, serializer, deserializer }
```

This makes the code much more declarative, allows for fewer checks (no name check) and fewer errors (in case a name cannot be found).

You you see what I mean?

**Comment by alcheng005** [comment]
Thanks for your detailed reply!

About the framework classes, that's actually a good point. We could build a template Dashport class, and then build out the OakDashport class by extending that template. Then developers can follow the template Dashport class and the OakDashport class to create Dashport classes of their own. This would prevent all the switch-like functionality that would become an issue as the number of server frameworks grows. We'll have to take a look at refactoring this, thanks for making that suggestion!

About passing the strategy instances themselves into dashport.authenticate and the (de)serializers, for these suggestions do you mean the developer would instantiate and export all strategies, serializers, and deserializers from different files(/one file) then import everything into wherever they needed? We would still like to be able to allow the developers to mix and match if strategies, serializers, and deserializers, if they wanted to. So then instead of

```typescript
// authentications.ts
import { serializer, deserializer } from "./path/to/serializer.ts"
export const googleAuthentication = { googleStrategy, serializer, deserializer }
export const otherAuthentication = { otherStrategy, serializer, deserializer }
```

where the developer is passing in serializer and deserializer for each Authentication declaration, what do you think about it working something like this?

```typescript
// dashport.config.ts
export const googStrat = new GoogleStrategy({...});
export const gitHubStrat = new GitHubStrategy({...});
export const serializer_A = (...) => {...};
export const serializer_B = (...) => {...};
export const deserializer_A = (...) => {...};
export const deserializer_B = (...) => {...};
```

```typescript
// server.ts
import * as configs from "./dashport.config.ts";

dashport.authenticate({
  strategy: configs.googStrat,
  serializers: [configs.serializer_A],
  deserializers: [config.deserializer_A]
});

dashport.authenticate({
  strategy: configs.gitHubStrat,
  serializers: [configs.serializer_A, configs.serializer_B],
  deserializers: [config.deserializer_A, configs.serializer_B]
});
```

The only tradeoff I can think of then is this would add a few lines wherever dashport.authenticate is inserted, cluttering up the server/route files a bit more. But that would probably be an okay tradeoff to have in order to not have dashport hold all the strategies, serializers, and deserializers.

**Comment by timreichen** [comment]
>where the developer is passing in serializer and deserializer for each Authentication declaration, what do you think about it working something like this?

works just as well, though I am not a fan of naming files with `config`, but that is up to the user. If they want to export the deserializers and strategies separately or as an object, they can do so. That is why modularity is great:)
I think, the important thing is, that you see right away what is happening with the `dashport.authenticate` call when passing data directly. If you setup an instance and then modify it, adding or removing strategies or (de)serializers in some other file, you might end up having unwanted behavior.

What I don't get is what the point is in passing multiple (de)serializers, since the session manager only needs one
```ts
return Object.values(serializers)[0](userData);
```
and _deserializeDecider calls
```ts
userInfo = Object.values(self._deserializers)[0](ctx.state._dashport.session);
```
I guess if the user wants to switch between deserializers, they could always before the `dashport.authenticate` call, or, since the (de)serializer is a function, inside that function.

**Comment by alcheng005** [comment]
Currently the (de)serializers are set up to only use the first value, but we were trying to set up the rest of Dashport so in the future we can add the functionality for developers to use multiple (de)serializers. We're not sure if there would actually be a case where a developer would want to use multiple (de)serializers, but we've added that functionality just in case. We might remove it and just use the singular (de)serializer passed in when authenticate is called. That might make more sense.

Also if you have time, would you be willing to meet up with the 1-5 of us (depending on availability) on discord/slack/zoom/google hangouts/etc to discuss some further details? We'd be interested in having a conversation with you to get some more insight.

**Comment by BAlexanderNance** [comment]
Thanks so much for the feedback Tim, we were really hoping to get a moment to talk real time with you, but ultimately we agreed with your assessment and will see in the most recent PR that we have adapted many of your suggestions.

Really appreciate the feedback, and we are excited for Dashport to grow!

**Comment by timreichen** [comment]
Sorry, I was very busy these days.
I saw that you made certain proposed changes. I think there is still room for improvements, also with the rep file structure. Feel free to hit me up on discord:
https://discord.gg/deno
username: timreichen [bundler]#1717
